CXX = g++
CXXFLAGS = -std=c++0x
CXXGLAGS += -wall
OBJS = 
SRCS = project6.cpp headerFinal.cpp 
HEADERS = headerFinal.h

Final: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o proj
#removed the headers from the rule to build line
