CXX = g++
CXXFLAGS = -std=c++0x
CXXGLAGS += -wall
OBJS = 
SRCS = fgmain.cpp f.cpp g.cpp
HEADERS = f.h g.h

fgmain: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o fgmain
#removed the headers from the rule to build line
